default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: motoNet_development

test:
  <<: *default
  database: motoNet_test

#production:
#<<: *default
#database: motoNet_production
#username: motoNet
#password: <%= ENV['MOTONET_DATABASE_PASSWORD'] %>
